import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBarComponent";
import TituloHeader from "@/components/TitleHeader";
import PrincipleButton from "@/components/PrincipleButton";

import Link from 'next/link'

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"]
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700"]
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Transparencia politica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    {label: "INICIO", href: "/"},
    {label: "PARTIDOS POLITICOS", href: "/Partidos"},
    {label: "CANDIDATOS", href: "/Candidatos"},
    {label: "PROPUESTAS", href: "/Propuestas"}
  ]
  return (
    <html lang="en" className = {`${montserrat.variable} ${inter.variable}`}>
      <body className="font-montserrat antialiased">
        <main className="mx-auto max-w-xl">
          <div className="px-4 py-4 lg:px-8">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
